# Generated by Django 3.2.8 on 2022-11-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='mobile',
            field=models.CharField(max_length=11, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='qq',
            field=models.CharField(max_length=20, null=True, verbose_name='QQ号码'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='weChat',
            field=models.CharField(max_length=20, null=True, verbose_name='微信账号'),
        ),
    ]
