# Generated by Django 3.2.8 on 2022-11-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='count',
            field=models.IntegerField(default=1, verbose_name='点赞数量'),
        ),
    ]
