# Generated by Django 3.2.8 on 2022-11-16 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0003_comment_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name': '音乐库', 'verbose_name_plural': '音乐库'},
        ),
        migrations.AlterField(
            model_name='music',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='music',
            name='pid',
            field=models.CharField(default='', max_length=10, verbose_name='父级目录'),
        ),
        migrations.AlterField(
            model_name='music',
            name='remark',
            field=models.CharField(default='', max_length=255, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='music',
            name='style',
            field=models.CharField(default='', max_length=255, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='music',
            name='url',
            field=models.CharField(default='', max_length=255, verbose_name='歌曲地址'),
        ),
        migrations.CreateModel(
            name='ShouCang',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.song', verbose_name='歌曲')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '音乐收藏',
                'verbose_name_plural': '音乐收藏',
                'db_table': 'shoucang',
            },
        ),
    ]
